# Generated by Django 3.2.9 on 2021-12-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211130_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='component_inventory',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
