# Generated by Django 3.2.9 on 2021-11-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
