# Generated by Django 3.2.9 on 2021-11-12 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
