# Generated by Django 3.2.9 on 2021-11-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
