# Generated by Django 3.2.9 on 2021-11-12 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20211112_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='module',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
