# Generated by Django 3.2.9 on 2021-11-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20211112_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='notes',
            new_name='description',
        ),
    ]
