# Generated by Django 3.2.9 on 2021-11-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_module_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
