# Generated by Django 3.2.9 on 2021-12-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_alter_module_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
