# Generated by Django 3.2.9 on 2021-12-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_auto_20211112_1447'),
        ('modules', '0009_modulecomponentidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='component',
            field=models.ManyToManyField(blank=True, related_name='module_component_to_identity', to='modules.ModuleComponentIdentity'),
        ),
        migrations.AlterField(
            model_name='modulecomponentidentity',
            name='component',
            field=models.ManyToManyField(related_name='component_identity_to_component', to='components.Component'),
        ),
    ]
