# Generated by Django 3.2.9 on 2021-12-27 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_auto_20211227_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='component',
            new_name='component_identities',
        ),
    ]
