# Generated by Django 3.2.9 on 2021-12-27 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_rename_component_module_component_identities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulecomponentidentity',
            options={'verbose_name_plural': 'Module Component Identities'},
        ),
        migrations.AddField(
            model_name='modulecomponentidentity',
            name='bom_order',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulecomponentidentity',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='modulecomponentidentity',
            unique_together={('module', 'bom_order')},
        ),
    ]
