# Generated by Django 3.2.9 on 2021-12-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_auto_20211227_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='bom_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='manual_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='manufacturer_page_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='modulargrid_link',
            field=models.URLField(blank=True),
        ),
    ]
