# Generated by Django 3.2.9 on 2022-01-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0014_auto_20220102_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecomponentidentity',
            name='designators',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='modulecomponentidentity',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modulecomponentidentity',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
