# Generated by Django 3.2.9 on 2022-01-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0015_auto_20220102_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecomponentidentity',
            name='designators',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='modulecomponentidentity',
            unique_together={('name', 'module')},
        ),
    ]
