# Generated by Django 3.2.9 on 2022-01-02 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0014_alter_component_ohms_unit'),
        ('modules', '0016_auto_20220102_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModuleComponentIdentity',
            new_name='ModuleBomListItem',
        ),
    ]
