# Generated by Django 3.2.9 on 2022-01-03 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0019_modulebomlistitem_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulebomlistitem',
            old_name='component',
            new_name='components_options',
        ),
    ]
