# Generated by Django 3.2.9 on 2022-01-31 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0020_rename_component_modulebomlistitem_components_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulebomlistitem',
            old_name='name',
            new_name='description',
        ),
        migrations.AlterUniqueTogether(
            name='modulebomlistitem',
            unique_together={('description', 'module')},
        ),
    ]
