columns = {
    "Capacitor":
        ["Description",
         "Manufacturer",
         "Voltage Rating",
         "Tolerance",
         "Suppliers",
         "Supplier Item #",
         "Price",
         "# in Inventory",
         "Inventory Location",
         "Add"],
    "Diode":
        ["Description",
         "Manufacturer",
         "Suppliers",
         "Supplier Item #",
         "Price",
         "# in Inventory",
         "Inventory Location",
         "Add"],
    "Jack":
        ["Description",
         "Manufacturer",
         "Suppliers",
         "Supplier Item #",
         "Price",
         "# in Inventory",
         "Inventory Location",
         "Add"],
    "Pin Header Strip":
        ["Description",
         "Manufacturer",
         "Suppliers",
         "Supplier Item #",
         "Price",
         "# in Inventory",
         "Inventory Location",
         "Add"],
    "Potentiometer":
        ["Description",
         "Manufacturer",
         "Suppliers",
         "Supplier Item #",
         "Price",
         "# in Inventory",
         "Inventory Location",
         "Add"],
    "Power Connector":
        ["Description",
         "Manufacturer",
         "Suppliers",
         "Supplier Item #",
         "Price",
         "# in Inventory",
         "Inventory Location",
         "Add"],
    "Resistor":
        ["Description",
         "Manufacturer",
         "Tolerance",
         "Suppliers",
         "Supplier Item #",
         "Price",
         "# in Inventory",
         "Inventory Location",
         "Add"],
    "SOIC IC":
        ["Description",
         "Manufacturer",
         "Suppliers",
         "Supplier Item #",
         "Price",
         "# in Inventory",
         "Inventory Location",
         "Add"],
}