# Generated by Django 3.2.9 on 2021-12-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_module_image'),
        ('users_extended', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='want_to_build_modules',
        ),
        migrations.AddField(
            model_name='userextended',
            name='want_to_build_modules',
            field=models.ManyToManyField(blank=True, null=True, related_name='want_to_build_modules', to='modules.Module'),
        ),
    ]
