# Generated by Django 3.2.9 on 2021-12-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_module_image'),
        ('users_extended', '0002_auto_20211206_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='built_modules',
        ),
        migrations.AddField(
            model_name='userextended',
            name='built_modules',
            field=models.ManyToManyField(blank=True, related_name='built_modules', to='modules.Module'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='want_to_build_modules',
            field=models.ManyToManyField(blank=True, related_name='want_to_build_modules', to='modules.Module'),
        ),
    ]
