# Generated by Django 3.2.9 on 2021-12-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_modulecomponentidentity'),
        ('users_extended', '0003_auto_20211214_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='built_modules',
            field=models.ManyToManyField(blank=True, related_name='built', to='modules.Module'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='want_to_build_modules',
            field=models.ManyToManyField(blank=True, related_name='want_to_build', to='modules.Module'),
        ),
    ]
