# Generated by Django 3.2.9 on 2022-01-09 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0020_rename_component_modulebomlistitem_components_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_inventory', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('built_modules', models.ManyToManyField(blank=True, related_name='built', to='modules.Module')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('want_to_build_modules', models.ManyToManyField(blank=True, related_name='want_to_build', to='modules.Module')),
            ],
            options={
                'verbose_name_plural': 'User Extended Properties',
            },
        ),
    ]
