# Generated by Django 3.2.9 on 2022-01-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0020_rename_component_modulebomlistitem_components_options'),
        ('components', '0017_auto_20220105_0502'),
        ('user_profile', '0002_auto_20220117_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='component_inventory',
            field=models.ManyToManyField(blank=True, through='user_profile.UserProfileComponentInventoryData', to='components.Component'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='want_to_build_modules',
            field=models.ManyToManyField(blank=True, related_name='want_to_build', to='modules.Module'),
        ),
    ]
