# Generated by Django 3.2.9 on 2022-01-23 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0020_rename_component_modulebomlistitem_components_options'),
        ('user_profile', '0004_auto_20220117_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofilecomponentinventorydata',
            options={'verbose_name_plural': 'User Component Inventory'},
        ),
        migrations.AlterModelOptions(
            name='userprofileshoppinglistdata',
            options={'verbose_name_plural': 'User Shopping List'},
        ),
        migrations.AddField(
            model_name='userprofileshoppinglistdata',
            name='bom_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.modulebomlistitem'),
        ),
        migrations.AddField(
            model_name='userprofileshoppinglistdata',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.module'),
        ),
    ]
