# Generated by Django 3.2.9 on 2022-01-23 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20220123_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShoppingLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofileshoppinglistdata',
            name='shopping_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.usershoppinglists'),
        ),
    ]
