# Generated by Django 3.2.9 on 2022-01-31 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20220123_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usershoppinglists',
            options={'verbose_name_plural': 'User-Defined, Named Shopping Lists'},
        ),
    ]
