# Generated by Django 3.2.9 on 2022-02-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_usershoppinglists_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilecomponentinventorydata',
            name='location',
            field=models.JSONField(default=[{'container_name': 'container', 'sub_container': {'container_name': 'box', 'sub_container': None}}]),
        ),
    ]
