# Generated by Django 3.2.9 on 2022-03-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_remove_userprofile_inventory_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileshoppinglistdata',
            name='shopping_list',
        ),
        migrations.AddField(
            model_name='userprofileshoppinglistdata',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
