# Generated by Django 3.2.9 on 2022-06-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_auto_20220630_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='component_inventory_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shopping_list_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
