# Generated by Django 3.2.9 on 2023-01-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_alter_userprofilecomponentinventorydata_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilecomponentinventorydata',
            old_name='number',
            new_name='quantity',
        ),
    ]
