# Generated by Django 3.2.9 on 2021-11-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name_plural': 'Components'},
        ),
    ]
