# Generated by Django 3.2.9 on 2021-12-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_auto_20211112_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='supplier',
            field=models.ManyToManyField(blank=True, to='components.ComponentSupplier'),
        ),
    ]
