# Generated by Django 3.2.9 on 2021-12-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_auto_20211228_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentmanufacturer',
            options={'verbose_name_plural': 'Component Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='componentsupplier',
            options={'verbose_name_plural': 'Component Supplier'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name_plural': 'Types'},
        ),
        migrations.AddField(
            model_name='component',
            name='manufacturer',
            field=models.ManyToManyField(blank=True, to='components.ComponentManufacturer'),
        ),
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('name', 'type')},
        ),
    ]
