# Generated by Django 3.2.9 on 2022-01-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_auto_20211231_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='supplier_item_no',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='types',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='component',
            unique_together=set(),
        ),
    ]
