# Generated by Django 3.2.9 on 2022-01-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_auto_20220102_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='tolerance',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='voltage_rating',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
