# Generated by Django 3.2.9 on 2022-01-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_auto_20220102_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='ohms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='ohms_unit',
            field=models.CharField(blank=True, choices=[('R', 'Ω'), ('kΩ', 'kΩ'), ('MΩ', 'MΩ')], max_length=2, null=True),
        ),
    ]
