# Generated by Django 3.2.9 on 2022-01-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_auto_20220102_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='farads',
            field=models.IntegerField(blank=True, help_text='If the component type involves capacitance, this value MUST be set.', null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='farads_unit',
            field=models.CharField(blank=True, choices=[('mF', 'mF'), ('μF', 'μF'), ('nF', 'nF'), ('pF', 'pF')], help_text='If the component type involves capacitance, this value MUST be set.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='ohms',
            field=models.IntegerField(blank=True, help_text='If the component type involves resistance, this value MUST be set.', null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='ohms_unit',
            field=models.CharField(blank=True, choices=[('R', 'Ω'), ('kΩ', 'kΩ'), ('MΩ', 'MΩ')], help_text='If the component type involves resistance, this value MUST be set.', max_length=2, null=True),
        ),
    ]
