# Generated by Django 3.2.9 on 2022-01-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0014_alter_component_ohms_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentsupplier',
            name='short_name',
            field=models.CharField(default='Tayda', max_length=30),
            preserve_default=False,
        ),
    ]
