# Generated by Django 3.2.9 on 2022-01-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0015_componentsupplier_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
