# Generated by Django 3.2.9 on 2022-01-05 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0016_types_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='types',
            options={'ordering': ['order'], 'verbose_name_plural': 'Types'},
        ),
        migrations.RemoveField(
            model_name='component',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='component',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='components.componentmanufacturer'),
            preserve_default=False,
        ),
    ]
