# Generated by Django 3.2.9 on 2022-02-10 06:40

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0020_auto_20220210_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=4, null=True),
        ),
    ]
